import type { Metadata } from "next";
import "../styles/globals.css"
import TanStackProvider from "@/providers/tanstack-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <TanStackProvider>
        <body className="min-h-full flex flex-col">{children}</body>
      </TanStackProvider>
    </html>
  );
}
