apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Using the base file
resources:
  - ../base

# This change the namesapece
namespace: kubernetes-example-homologacao

# This change the base file on deployment
replicas:
  - name: nginx-deployment
    count: 1

images:
  - name: nginx_k8s_image
    newTag: homolog