apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-test-pod
  labels:
    app: test-environment
spec:
  containers:
  - name: ubuntu-container
    image: custom_ubuntu_image
    imagePullPolicy: IfNotPresent
    # command: ["/bin/bash", "-c", "sleep infinity"]
    command: ["/bin/bash", "-c", 'echo "The valye on the secret is $LEANDRO_ENV" && sleep infinity ']
    # env:
    # - name: LEANDRO_ENV
    #   valueFrom:
    #     secretKeyRef:
    #       name: my_ultra_secret_key    # Name of the Secret object you will create
    #       key: secret-key        # Key inside the Secret object
