apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-test-pod-with-secret
  labels:
    app: test-environment
spec:
  containers:
  - name: ubuntu-container
    image: custom_ubuntu_image
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash", "-c", 'echo "The valye on the secret is $LEANDRO_ENV" && sleep infinity ']
    env:
    - name: LEANDRO_ENV
      valueFrom:
        secretKeyRef:
          name: my-calopsita-secret    # Name of the Secret object you will create
          key: message                 # Check the key with: kubectl get secret my-calopsita-secret -o yaml -> Is right after data:
